xychart-beta
    title "User experience vs. system response time"
    x-axis "Response time" ["0-100ms", "100-400ms", "400ms-1s", "1-3s", "3-5s", "5s+"]
    y-axis "User experience quality" 0 --> 10
    line [9.5, 9, 7, 4, 2, 1]